FROM node:8-alpine
WORKDIR /
RUN npm init -y && \
    npm install \
      eslint@4.19.0 \
      eslint-formatter-pretty@1.3.0 \
      eslint-config-standard@11.0.0 \
      eslint-plugin-standard@3.0.1 \
      eslint-plugin-promise@3.7.0 \
      eslint-plugin-import@2.9.0 \
      eslint-plugin-node@6.0.1 && \
    rm -rf /usr/share/man/tmp/* \
    /root/.npm /root/.node-gyp \
    /usr/lib/node_modules

ENTRYPOINT ["/node_modules/.bin/eslint", "--format=pretty", "."]
